date_personale = []
nume = input("Introduceți numele: ")
date_personale.append(nume)
prenume = input("Introduceți prenumele: ")
date_personale.append(prenume)
varsta = input("Introduceți vârsta: ")
date_personale.append(varsta)
inaltimea = input("Introduceți înălțimea: ")
date_personale.append(inaltimea)
ocupatia = input("Introduceți ocupația: ")
date_personale.append(ocupatia)
print("Lista date_personale:", date_personale)